//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using strange.framework.context.api;
using strange.extensions.enhancedLogging.impl;


namespace strange.extensions.enhancedLogging
{
	public class ConsoleLoggingExtension : IExtension
	{
		public void Extend (IContext context)
		{
			context.AddLogTarget(new ConsoleLogTarget(context));
		}
	}
}

